# Generated by Django 4.2 on 2023-04-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_app', '0002_order_customer_name_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_mail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(),
        ),
    ]
